Chore: Add links to relevant pages
LABS-EU3/shopping_cart_frontend pull request #28
Opened 2020-01-08 14:46 UTC by shaunorpen

## Description
Made sure the text links on the bottom of many pages all work.
## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Checklist
Remove any items which are not applicable.
- [x] I have performed a self-review of my own code
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works .
- [x] New and existing unit tests pass locally with my changes
## Link to Trello card
https://trello.com/c/VzLDPWXY/55-tidy-up-links

2020-01-08 15:39 UTC, DimejiAre requested changes
@shaunorpen some other pages need this, maybe we should add to this PR, like the create items page should link to /inventory on success and cancel.

2020-01-08 16:46 UTC, shaunorpen commented
Ok. I'll have a look at that.

2020-01-08 17:03 UTC, shaunorpen commented
@DimejiAre I've had a look. It looks like those links will be implemented with history.push rather than <Link>, so I suggest dealing with them in a separate PR if you agree? This PR currently only focuses on links which were previously implemented with <a> tags.

2020-01-09 09:46 UTC, DimejiAre approved these changes

2020-01-09 09:50 UTC, merged