ft: add delete store functionality
LABS-EU3/shopping_cart_frontend pull request #44
Opened 2020-01-10 11:31 UTC by aapetsi

## Description
Describe change or new feature here.
## Type of change
Please delete options that are not relevant.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
## Checklist
Remove any items which are not applicable.
- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works .
- [x] New and existing unit tests pass locally with my changes
## Link to Trello card

2020-01-10 11:32 UTC, aapetsi commented
![](https://github.trello.services/images/mini-trello-icon.png) [/profile](https://trello.com/c/UVsiHdjA/74-profile)

2020-01-13 09:49 UTC, shaunorpen requested changes
Bit confused about this PR. The title is delete store. The branch is delete account. Which is it?

Some questions and suggestions:

1. There's no 'Are you sure' message when you click 'delete account'. You just get a pop-up saying your account has been deleted. I think we should have a confirmation dialog.

2. After the account is deleted I'm redirected to dashboard. I would have thought I should be redirected to login / register? I think deleting account should clear the token from local storage otherwise when you visit / you get redirected to dashboard, which looks broken as there's no longer any account data to display.

2020-01-13 12:15 UTC, DimejiAre commented
@aapetsi A modal was created for the delete item functionality. The one you used for the delete account looks very different. Try and reuse already existing components/design for uniformity and consistency across the app. It also saves time.

2020-01-13 12:39 UTC, aapetsi commented
> @aapetsi A modal was created for the delete item functionality. The one you used for the delete account looks very different. Try and reuse already existing components/design for uniformity and consistency across the app. It also saves time.

@DimejiAre it's been fixed

2020-01-13 14:33 UTC, shaunorpen requested changes
Just a minor update to the delete modal to suggest. Great work!

2020-01-13 14:33 UTC, shaunorpen commented on src/components/EditProfile/EditProfile.js
> +      title: 'Are you sure you want to delete your account item?',
Suggestion: Update this to read 'Are you sure you want to delete your account?'.

2020-01-13 14:36 UTC, shaunorpen approved these changes

2020-01-13 14:42 UTC, merged