Checkout forms and single page view
LABS-EU3/shopping_cart_frontend pull request #62
Opened 2020-01-20 14:27 UTC by kip-guile

## Description
Checkout forms and single page view
## Type of change
Please delete options that are not relevant.
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
## Checklist
Remove any items which are not applicable.
- [X] I have performed a self-review of my own code
- [X] My code follows the style guidelines of this project
- [X] My changes generate no new warnings
## Link to Trello card
https://trello.com/c/AKIJwdLO

2020-01-20 14:37 UTC, shaunorpen requested changes
Minor change: Suggest that delivery address is only captured if delivery is selected. At the moment it appears it's always required?

2020-01-20 14:38 UTC, kip-guile commented
Fixed the issue. You can review now

2020-01-20 14:44 UTC, shaunorpen submitted a review, later dismissed
It looks like you just changed the validation to make it optional? I think the field should not be visible if the buyer asks to collect. Make sense?

2020-01-21 15:11 UTC, DimejiAre approved these changes

2020-01-21 15:17 UTC, merged